var items = { 'argy':
    {
        'id': 'argy',
        'price': 0, 
        'name': 'Argy Bee', 
        'stamp_url':'images/stamps/argy_bee.png', 
        'stamp_name':'argy_bee',
        'color1': '#ff0000',
        'color1_name': 'Red',
        'color2': '#00ff00',
        'color2_name': 'Green',
        'color3': '#0000ff',
        'color3_name': 'Blue',
        'background_url': 'images/backgrounds/photoshop.png',
        'background_name': 'Photosharp'
    },
    'apple':
    {
        'id':'apple',
        'price': 5,
        'name': 'Apple', 
        'stamp_url': 'images/stamps/apple.png',
        'stamp_name': 'Apple',
        'color1': '#9a1419', 
        'color1_name': 'Crimson',
        'color2': '#e92d34',
        'color2_name': 'Red',
        'color3': '#2c865b',
        'color3_name': 'leaf',
        'background_url': 'images/backgrounds/background_apple.png',
        'background_name': 'Apple',
    },
    'palomino':
    {
        'id':'palomino',
        'price': 9,
        'name': 'Palomino', 
        'stamp_url': 'images/stamps/bw_horse_3.png',
        'stamp_name': 'Palomino',
        'color1': '#d88e45', 
        'color1_name': 'Palomino Dark',
        'color2': '#f6dbbd',
        'color2_name': 'Palomino Light',
        'color3': '#fefaf7',
        'color3_name': 'Palomino Blonde',
        'background_url': 'images/backgrounds/palomino.png',
        'background_name': 'Palomino',
    },
    'bay':
    {
        'id':'bay',
        'price': 16,
        'name': 'Bay', 
        'stamp_url': 'images/stamps/bw_horse_4.png',
        'stamp_name': 'Bay',
        'color1': '#6d3e20', 
        'color1_name': 'Bay Dark',
        'color2': '#d8a578',
        'color2_name': 'Bay Light',
        'color3': '#302f2b',
        'color3_name': 'Black Hair',
        'background_url': 'images/backgrounds/bay.png',
        'background_name': 'Bay',
    },
    'chestnut':
    {
        'id':'chestnut',
        'price': 16,
        'name': 'Chestnut', 
        'stamp_url': 'images/stamps/bw_horse_5.png',
        'stamp_name': 'Chestnut',
        'color1': '#774c3c', 
        'color1_name': 'Chestnut Dark',
        'color2': '#f3b890',
        'color2_name': 'Chestnut Light',
        'color3': '#503232',
        'color3_name': 'Chestnut Hair',
        'background_url': 'images/backgrounds/chestnut.png',
        'background_name': 'Chestnut',
    },
    'twilight':
    {
        'id':'twilight',
        'price': 20,
        'name': 'Twilight', 
        'stamp_url': 'images/stamps/twilight.png',
        'stamp_name': 'Mark',
        'color1': '#d098e4', 
        'color1_name': 'Parple',
        'color2': '#24386d',
        'color2_name': 'Dark Blue',
        'color3': '#f64188',
        'color3_name': 'Pink',
        'background_url': 'images/backgrounds/little_pony.png',
        'background_name': 'Chestnut',
    },
    'hay':
    {
        'id':'hay',
        'price': 25,
        'name': 'HAY GUYS',
        'stamp_url': 'images/stamps/hay.png',
        'stamp_name': 'Hay',
        'color1': '#faf5a0', 
        'color1_name': 'Mello Yello',
        'color2': '#efe63e',
        'color2_name': 'Superior Yellow',
        'color3': '#bcb529',
        'color3_name': 'Mustard Town',
        'background_url': 'images/backgrounds/field.png',
        'background_name': 'Field',
    }
};

var item_id_list = ['argy', 'apple', 'palomino', 'bay', 'chestnut', 'twilight', 'hay'] 
